### ISSUE TITLE
Feature request: Multiple tests per file

### ISSUE THREAD

**Issue by segeljakt** [jfecher/golden-tests#4]
It does not seem possible to have multiple goldentests in the same source file. It's not necessary but it might be useful to be able to test things like code generation and pretty printing using the same source file.

**Comment by jfecher** [comment]
(Sorry I missed this!)

Definitely a neat idea. I certainly have a few tests that are almost completely copy pasted with one for parsing and another for name resolution/type checking. I could see this as a potential win especially for larger projects to cut down on the amount of test files.

I think this would also require each command be printed to distinguish which command in a file failed. This isn't too hard but may clutter the output and raise more questions like should the command be omitted from tests with only one "args:" line, and should it always be printed if "verbose" is set?

I think I'm currently leaning towards not adding it since tests should ideally be the minimal size to test a given feature which seems to conflict with using the same file for multiple tests. The alternative is copy pasting a file which I'm guilty of but also in comparison lets me organize my tests with folders (separate folders for parsing, nameresolution, codegen, etc.) and lets me update a file when a command files without fear I'm messing up another command.

The idea itself is still interesting though, I think it can be revisited it in the future if the current design leads to too much test bloat.

**Comment by segeljakt** [comment]
Hi, sorry for not responding. I realised the solution to this is already provided! You can defined multiple `TestConfig`s for the same file. I have

```rust
use goldentests::{TestConfig, TestResult};

#[test]
fn run_golden_tests() -> TestResult<()> {
    TestConfig::new("../target/debug/arc-script", "tests/goldentests", "--[ARC] ")?.run_tests()?;
    TestConfig::new("../target/debug/arc-script", "tests/goldentests", "--[MLIR] ")?.run_tests()?;
    Ok(())
}
```

And then:

```
fun test() {
  let c = true in
  let x = 3 in
  if c { x } else { x }
}

--[ARC] args: --verbose --check file
--[ARC] expected stdout:
--[ARC] fun test() {
--[ARC]     (let c: bool = (true):bool in
--[ARC]     (let x: i32 = (3):i32 in
--[ARC]     (let x3: i32 = (if (c):bool {
--[ARC]         (x):i32
--[ARC]     } else {
--[ARC]         (x):i32
--[ARC]     }):i32 in
--[ARC]     (x3):i32):i32):i32):i32
--[ARC] }

--[MLIR] args: --mlir --check file
--[MLIR] expected stdout:
--[MLIR] func @%x_0() -> (i32) {
--[MLIR]     %x_1 = "arc.constant"() { value = true : i1 }: () -> i1
--[MLIR]     %x_2 = "arc.constant"() { value = 3 : i32 }: () -> i32
--[MLIR]     %x_3 = "arc.if"(%x_1) ({
--[MLIR]         "arc.yield"(%x_2) : (i32) -> ()
--[MLIR]     },{
--[MLIR]         "arc.yield"(%x_2) : (i32) -> ()
--[MLIR]     }) : (i1) -> i32
--[MLIR]     "std.return"(%x_3) : (i32) -> ()
--[MLIR] }
```

Thanks for the excellent tool.

**Comment by jfecher** [comment]
Very cool, I didn't even think of such a usage!
