### ISSUE TITLE
Snapshot testing

### ISSUE THREAD

**Issue by segeljakt** [jfecher/golden-tests#5]
This might be a tall order. I am wondering how hard it would be to extend `golden-tests` so that it can automatically update the expected-output when needed. Currently I need to manually update the expected output whenever it changes.

**Comment by jfecher** [comment]
Usually the purpose of golden tests are to assert the output of something doesn't change, and to require human intervention when it does. E.g. I use it for (among other things) asserting that given an example program that the correct types are always inferred. If I ever change my type inference in a way that those expected types change I'd expect an error, then I'd verify whether the new output is expected or not, and if so copy-paste the new output from the terminal, or otherwise fix the type inference until it gave me the old results again.

Perhaps I'm missing something or not understanding though. Can you elaborate more on your use case?

**Comment by segeljakt** [comment]
Hi, sorry for the late response. I use goldentests for the same thing. The main reason I asked is because of laziness when it comes to manual copy-pasting 😅 . It's not close to being crucial, so if no one else experiences the same problem, I don't think it's worth implementing.

**Comment by jfecher** [comment]
I think to solve the "only automatically update the golden-tests sometimes" problem would require some CLI (y/n) confirmation interaction from the user so they can specify whether they want it updated or not. I'm not sure is possible while running `cargo test`, so for now I'll leave out this feature unless more people want it and I can hopefully come up with a better design.
